### PR TITLE
Added support for fitted coordinate system (IFittedCoordinateSystem impl...

### PR DESCRIPTION
**Pull request by vicocz**
I would like to commit simple implementation of IFittedCoordinateSystem to the master branch.

### CODE REVIEW

**Comment by DGuidi** [comment]
@FObermaier what do you think?

**Comment by FObermaier** [comment]
I have no clue what a fitted coordinate system is.
Maybe a unit test will show?
Otherwise I have no objection.

**Comment by vicocz** [comment]
Let me explain it little bit :)
Let's start from the GeoAPI interface IFittedCoordinateSystem which is described: "A coordinate system which sits inside another coordinate system. The fitted coordinate system can be rotated and shifted, or use any other math transform to inject itself into the base coordinate system."

The implementation covers situation of a factory which uses their local coordinate system (based on translate and rotation) to keep building plans simple. The local coordinate system is based on well known coordinate system.

Example of local coordinate system from Germany:
- it defines affine transform from local coordinate system NAU (Kraftwerk Niederaußem) into Gauß-Krüger-coordinate system (EPSG:31467). The transformation order is following: translate, rotate, scale.

Start point: X=2040,000m Y=1590,000m
Offset: X=44886,640m Y=49481,278m
Target point: X=46926,640m Y=51071,278m
Rotation around target point: 27,9343 degrees
Scale: 1,0000

This might be used in a unit test, but nowadays there is no class for affine transfromation.

**Comment by FObermaier** [comment]
Now that makes sense to me, too.
What is lacking now is an implementation of an  affine IMathTransform, is that right?

**Comment by vicocz** [comment]
Implementation of an affine transfrom would be nice, but it's quite complicated class (like it's mentiond in IMathTransformFactory).
I was using some simple immutable 2D affine transformation to get it worked. Such implementation is usable for unit test only.

**Pull request merged**
