### PR TITLE
Tweak how we use spans

### PR DESCRIPTION
**Pull request by airbreather**
- Base implementations now have virtual methods that can be overridden as appropriate to provide optimized versions for any of the following layouts:
    - `[x0, y0, z0, x1, y1, z1, ..., xn, yn, zn]`
    - `[x0, y0, x1, y1, ..., xn, yn, z0, z1, ..., zn]`
    - `[x0, x1, ..., xn, y0, y1, ..., yn, z0, z1, ..., zn]`

All built-in algorithms now only override the one-by-one variants.  The point of allowing subclasses to override for spans (and allowing different layouts) is to allow implementations that use SIMD and/or auxiliary DLLs for their implementations.  There ought not to be a **particularly** significant advantage to using spans the way we were doing before.

### CODE REVIEW

**Comment by airbreather** [comment]
When looking at this, make sure to hide whitespace-only changes:
image

**Comment by airbreather** [comment]
> We should come up with a performance test to help find a conclusion on this

Perhaps, but it's not **just** performance (especially not performance **of ProjNet4GeoAPI itself**) that prompted my reply, but a combination of how easy it is for dependents to use it, how easy it is to implement new projections, and what I'm going to call "ideal performance".

## "Ideal performance"...
I don't know if there's a term for this already, but when I say "ideal performance", I mean the best performance that the library could possibly achieve (without breaking changes) when the caller provides the system with all the information that they have, without having to circumvent too many abstractions.

In other words, if someone has a `PackedDoubleCoordinateSequence` with `Dimension = 2` and `Measures = 0` and they want to transform it in-place, then they can do:
```csharp
MapProjection theProjection = GetTheProjection();
PackedDoubleCoordinateSequence seq = GetTheSequence();
Span<XY> xys = MemoryMarshal.Cast<double, XY>(seq.GetRawCoordinates());
theProjection.Transform(xys, xys);
```

and then we have the **option** (if we choose to optimize this path) to call out to a native DLL that implements the routine as efficiently as the platform allows... but we probably won't, because the built-in is probably good enough.

If someone has [a coordinate sequence that stores the points laid out SoA-style](https://github.com/airbreather/NetTopologySuite.Optimized/blob/e0c2f77570da79143cad44668cf1a2d8475d04ac/NetTopologySuite.Optimized/SOACoordinateSequence.cs) (because, perhaps, they do other SIMD operations), then they should be able to do:
```csharp
MapProjection theProjection = GetTheProjection();
SOACoordinateSequence seq = GetTheSequence();
Span<double> xs = seq.GetXs();
Span<double> ys = seq.GetYs();
theProjection.Transform(xs, ys, xs, ys);
```

and then we have the **option** (again, if we choose to optimize it) to call out to a different native DLL (or use vector intrinsics coming in .NET Core 3.0 :grin:) to transform multiple points at a time... but again, we probably won't, because the built-in is still probably good enough.

**BUT**... suppose (purely hypothetically, of course) that someone has been passing around `MapProjection` instances throughout their application, and they just so happen to find that there could be some throughput benefits by dispatching to a different implementation upon seeing a particular set of parameter values.
- This different implementation might have pre-computed some of the calculations that become invariant after doing so, rewritten the logic flow to maximize ILP (including, perhaps, unrolling loops), and even perhaps used advanced SIMD intrinsics that somehow only Intel's C++ compiler even bothers to offer (though who would be crazy enough to do th[at?](https://github.com/airbreather/AirBreather.Projections/blob/62b308b939f91d3af7c6d986ff6fdebaf9d76f13/proj-native/proj.c#L138-L150)).
- Such a hypothetical individual might very much appreciate the opportunity to override a method on `MapProjection` that accepts an input in a compatible shape and uses the optimized code path when it sees that it can, falling back to the not-as-optimized version in all other cases.

This kind of thing is what I'm referring to when I talk about performance (which is why the comment was originally logged in GeoAPI since `IMathTransform` is an even better place for this)... basically giving people:
1. something that's usable out-of-the-box and probably fast enough most of the time and
1. the tools that they would need in order to selectively eliminate bottlenecks

**Comment by airbreather** [comment]
> we have the **option** (if we choose to optimize this path) to call out to a native DLL that implements the routine as efficiently as the platform allows

heh... it wouldn't even be **just** to optimize performance: I think all of the "bulk" methods I added can translate to efficient calls to [PROJ.4's `proj_trans_generic` function](https://proj4.org/development/reference/functions.html#c.proj_trans_generic) if we wanted to make a P/Invoke wrapper around that to expand the list of projections we support :nerd_face:.

**Comment by FObermaier** [comment]
@airbreather,  I've confirmed that your approach does not imply decrease of performance so I'm happy with persuing your approach.

Let's clean it up:
* What do you think needs to be added to GeoAPI / GeoAPI.CoordinateSystems.

**Comment by airbreather** [comment]
> What do you think needs to be added to GeoAPI / GeoAPI.CoordinateSystems.

That depends on which of NetTopologySuite/GeoAPI#67 or NetTopologySuite/GeoAPI#68 (or neither) we choose to do for 2.0... my ideal would be along the lines of NetTopologySuite/GeoAPI#68: replace `IMathTransform` with an abstract base class that does the same thing I did for `MathTransform` in here, namely, one abstract "one-by-one" method and lots of virtual methods calling it.

**Comment by FObermaier** [comment]
`SequenceCoordinateConverterBase` should be changed to `SequenceTransformerBase` so that it has access to the `MathTransform` object and can decide on its own which of the `Transform` overloads suits its data structure best.

**Comment by airbreather** [comment]
> `SequenceCoordinateConverterBase` should be changed to `SequenceTransformerBase` so that it has access to the `MathTransform` object and can decide on its own which of the `Transform` overloads suits its data structure best.

Ahh, yeah, I was thinking about that type too... my thought on it was that it should have something like:

```csharp
public virtual SomeNewEnum GetIdealLayout(ICoordinateSequence coordinateSequence)
{
    return SomeNewEnum.DoesntMatter;

    // DoesntMatter: we pick based on what's most efficient for us (or arbitrarily)
    // other defined values tell us which of the variants is most efficient for the sequence
}
```

And then expose methods to copy to/from the different layouts.

The idea being that it will **work** for all different possible sequences, but almost all sequences will naturally copy to/from a particular layout more efficiently than any other (because the coordinates are already in that order to begin with), and so we will want to know which of the different variants would be best for each sequence.

**Pull request merged**
