### PR TITLE
Remove GeoAPI dependency

### PR DESCRIPTION
**Pull request by FObermaier**
* Include necessary GeoAPI interfaces and value classes
* Remove unnecessary GeoAPI interfaces
* Make necessary code adjustments

### CODE REVIEW

**Comment by FObermaier** [comment]
@airbreather , I finally got around to removing GeoAPI from ProjNet4GeoAPI.
Could you please help on updating `csproj` files to versioning scheme as used in NTS now?
Feel free to use this branch.

**Comment by airbreather** [comment]
> Could you please help on updating `csproj` files to versioning scheme as used in NTS now?

That's all taken care of now, with Travis-CI builds and everything.

**Comment by FObermaier** [comment]
Thanks. A few more questions:
* We don't need the `*.nuspec` file any more, do we.
* the package is labeled `ProjNet4GeoAPI`. Now that we have removed the GeoAPI we should reflect that in the package name. We could either ask for ownership of https://www.nuget.org/packages/ProjNet/ or just label it `Proj.Net`.

**Comment by airbreather** [comment]
> We don't need the `*.nuspec` file any more, do we.

Correct; I removed it from the solution's associated files, but then I forgot to delete it entirely.

> the package is labeled `ProjNet4GeoAPI`. Now that we have removed the GeoAPI we should reflect that in the package name. We could either ask for ownership of https://www.nuget.org/packages/ProjNet/ or just label it `Proj.Net`.

There's already a [Proj.NET](https://www.nuget.org/packages/Proj.NET/) too...

Maybe `NetTopologySuite.ProjNet`?

**Comment by FObermaier** [comment]
We now have ownership of `ProjNET` package. So we can move on or would you like to do some more reviewing @airbreather?

**Comment by airbreather** [comment]
> So we can move on or would you like to do some more reviewing @airbreather?

I think we can move on from this PR.  I keep getting distracted by unrelated things I want to do, and all the style changes happening at the same time make it really hard to go through.  I'm sure it's fine.

**Comment by SamuelEnglard** [comment]
Why was GeoAPI reference removed? Now I can't use this with NTS since they have different `IProjection`s

**Comment by airbreather** [comment]
@SamuelEnglard please open a new issue explaining the problem

**Pull request merged**
